/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#ffb77b',
        'surface-dim': '#131313',
        'inverse-surface': '#e5e2e1',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#261a00',
        'tertiary-fixed': '#e5e2e1',
        'primary-fixed-dim': '#fbbc00',
        'on-secondary': '#4d2700',
        'on-primary-container': '#6d5000',
        'surface-tint': '#fbbc00',
        surface: '#131313',
        'on-error': '#690005',
        'inverse-on-surface': '#313030',
        'on-surface-variant': '#d4c5ab',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'surface-bright': '#393939',
        'on-secondary-fixed-variant': '#6d3a00',
        'surface-container-highest': '#353534',
        'on-tertiary-fixed': '#1c1b1b',
        'inverse-primary': '#795900',
        'surface-container-high': '#2a2a2a',
        'on-primary': '#402d00',
        'tertiary-container': '#cbc9c8',
        'surface-container-low': '#1c1b1b',
        'outline-variant': '#504532',
        outline: '#9c8f78',
        tertiary: '#e8e5e4',
        'on-tertiary': '#313030',
        'primary-container': '#ffbf00',
        'surface-container': '#201f1f',
        'on-surface': '#e5e2e1',
        'on-tertiary-fixed-variant': '#474746',
        'on-background': '#e5e2e1',
        'surface-container-lowest': '#0e0e0e',
        'primary-fixed': '#ffdfa0',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-secondary-container': '#ffb270',
        secondary: '#ffb77b',
        'on-primary-fixed-variant': '#5c4300',
        background: '#131313',
        primary: '#ffe2ab',
        'on-secondary-fixed': '#2e1500',
        'surface-variant': '#353534',
        'on-tertiary-container': '#555454',
        'secondary-container': '#7a4100',
        'secondary-fixed': '#ffdcc2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '32px',
        'container-max-width': '1280px',
        'section-gap': '120px',
        base: '8px',
        'margin-desktop': '80px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'headline-md': ['"Playfair Display"', 'serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['"Playfair Display"', 'serif'],
        'display-lg': ['"Playfair Display"', 'serif'],
        'headline-lg': ['"Playfair Display"', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' },
        ],
        'display-lg-mobile': [
          '40px',
          { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'display-lg': [
          '64px',
          { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}

