version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: savora_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: savora_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/savora
      - JWT_SECRET=savora_jwt_secret_key_2026_premium_dining
      - JWT_EXPIRE=7d
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: savora_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
